language: node_js
node_js:
  - stable

env:
  CI: false

install:
  - npm install

script:
  - npm run build

deploy:
  provider: heroku
  api_key: ${HEROKU_API_KEY}
  app:
    master: ag-pranjal-sudoku-visualizer
